import path from 'node:path';
import { cloudflareTest, readD1Migrations } from '@cloudflare/vitest-plugin';
import { defineConfig } from 'vitest/config';

// Workers-runtime project: tests that touch D1 (or anything else that needs
// real Workers/Miniflare semantics — transactions inside db.batch, unique
// constraint errors, etc). Always local — Miniflare simulates D1 entirely
// on-disk/in-memory; the real (remote) database is never touched by tests,
// regardless of what `database_id` is configured in wrangler.jsonc.
export default defineConfig(async () => {
  const migrations = await readD1Migrations(path.join(import.meta.dirname, 'migrations'));

  return {
    test: {
      include: ['worker/**/*.workers.test.ts'],
      setupFiles: ['./worker/booking/test-setup/apply-migrations.ts'],
    },
    plugins: [
      cloudflareTest({
        // The site's real wrangler.jsonc `main` is generated by `astro build`
        // into dist/server/ and doesn't exist as source pre-build, so it
        // can't be used as the test harness's entry. These tests only touch
        // worker/booking/db.ts directly (no routes exist yet), so a trivial
        // dummy entry plus a directly-declared D1 binding is enough; the
        // binding name (BOOKINGS_DB) matches wrangler.jsonc's real one.
        main: './worker/booking/test-setup/dummy-entry.ts',
        miniflare: {
          d1Databases: ['BOOKINGS_DB'],
          // Test-only binding carrying the parsed migrations, so the setup
          // file can apply them before each test file runs.
          bindings: { TEST_MIGRATIONS: migrations },
        },
      }),
    ],
  };
});
