import path from 'node:path';
import { cloudflareTest, readD1Migrations } from '@cloudflare/vitest-plugin';
import { defineConfig } from 'vitest/config';

// Routing-level integration tests: run against the REAL built Worker entry
// (dist/server/wrangler.json, generated by `astro build`), not a dummy one.
// This is the only project that can catch a routing regression — a new
// route not actually reaching its handler, or a change that breaks static
// asset serving — because it's the only one exercising Astro's own request
// dispatch (see worker-entry's `handle()`) rather than calling worker/
// modules directly. Requires a fresh `npm run build` first (wired via the
// `pretest:integration` npm script) since it reads the build output.
export default defineConfig(async () => {
  const migrations = await readD1Migrations(path.join(import.meta.dirname, 'migrations'));

  return {
    test: {
      include: ['worker/**/*.integration.test.ts'],
      setupFiles: ['./worker/booking/test-setup/apply-migrations.ts'],
      testTimeout: 15000,
    },
    plugins: [
      cloudflareTest({
        // Not dist/server/wrangler.json itself — see scripts/prepare-integration-test-config.mjs.
        wrangler: { configPath: './dist/server/wrangler.integration-test.json' },
        miniflare: {
          bindings: { TEST_MIGRATIONS: migrations },
        },
      }),
    ],
  };
});
