// Minimal Worker entry for the D1 test harness only. The real site's Worker
// entry is generated by `astro build` into dist/server/ at build time and
// doesn't exist as a resolvable source file, so these tests — which only
// exercise worker/booking/db.ts directly against env.BOOKINGS_DB, not real
// routes — bring their own trivial entry instead of pointing at it.
export default {
  async fetch(): Promise<Response> {
    return new Response('not used — see worker/booking/*.workers.test.ts', { status: 404 });
  },
};
